{{ if .Values.deployment.enabled }}
{{ with .Values.global }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  {{- if not $.Values.hpa.enabled }}
  replicas: {{ .replicas }}
  {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
  strategy:
    rollingUpdate:
      {{- if .maxSurge }}
      maxSurge: {{ .maxSurge }}
      {{- end }}
      {{- if .maxUnavailable }}
      maxUnavailable: {{ .maxUnavailable }}
      {{- end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $.Release.Name }}
        image: {{ .image }}
        imagePullPolicy: Always
        env: 
        - name: VERSION
          value: {{ .version }}
        - name: DEBUG
          value: "{{ .debug }}"
        - name: ALIVE_TIMEOUT
          value: "{{ .timeout }}"
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            scheme: HTTP
            path: /alive
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /alive
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
{{ end }}
{{ end }}
