apiVersion: v1
name: MyApp
description: MyApp test application
type: application
version: 0.0.1
appVersion: 0.0.1

keywords:
  - myapp
  - demo
  - k3d
  - web

maintainers:
  - name: Dr Magel
    email: dr.magel@example.com