{{ $name := .Release.Name }}
{{ $namespace := .Release.Namespace }}
{{ $enabled := not (.Values.postgresql.enabled) }}
{{ $global := $.Values.global }}

{{ if $enabled }}
{{ with $global }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  serviceName: {{ $name }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .image }}:{{ .tag }}
        imagePullPolicy: Always
        env:
        - name: USE_POSTGRESQL
          value: {{ not $enabled | quote }}
        - name: ADMIN_PASSWORD
          value: {{ .auth.password | quote }}
        - name: ADMIN_USERNAME
          value: {{ .auth.username | quote }}
        ports:
        - containerPort: {{ .port }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            scheme: HTTP
            path: /health
            port: {{ .port }}
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /health
            port: {{ .port }}
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health
            port: {{ .port }}
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClassName }} 
      resources:
        requests:
          storage: {{ .storageSize }}
{{ end }}
{{ end }}
