name: Green Workflow

on:
  push:
    branches:
      - dimar-green-work

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-on-dnd:
    runs-on: arc-runner-arm64-dind

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script on docker container
        run: |
          echo "Running on self-hosted runner 'arc-runner-arm64-dind'"
          docker images || true
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            ubuntu:24.04 \
            ls -R /work
          sleep 900

  run-on-tools:
    runs-on: arc-runner-arm64-tools

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          echo "Running on self-hosted runner 'arc-runner-arm64-tools'"
          (cd ${{ github.workspace }}; pwd)
          ls -R ${{ github.workspace }}
          sleep 900
