name: Green Workflow

on:
  push:
    branches:
      - dimar-green-work

jobs:
  run-on-dnd:
    runs-on: arc-runner-arm64-dind

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Running on self-hosted runner 'arc-runner-arm64-dind'" && sleep 900

  run-on-tools:
    runs-on: arc-runner-arm64-tools

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Running on self-hosted runner 'arc-runner-arm64-tools'" && sleep 900
